### ISSUE TITLE
Investigation on using socketcluster for UE4 under android and other devices

### ISSUE THREAD

**Issue by RKRewind** [ziicreater/socketcluster-client-ue4#1]
Hello,

I'm about to check the feasibility of porting this plugin for android. We need a web socket solution to be used on a UE4 app on client side, and this plugin seem really promising.
Just wanted to ask if you see any major difficulties over such porting, or you have any suggestion to share. So far I gave only a glance to the code and everything seem fine with a possible Android port, is it flagged not supported due to lack of  testing?

Thank you already for this open source plugin which should make my work so much easier :)

**Comment by SloppyShovel** [comment]
Hi,

Sorry for the late response,

Yes, the code should work on android or any platform, the reason is lack of testing, we are working on getting it tested on different platforms, it does not use any specific platform resources in the code as you may have seen, the reason was to make it run on any platform, but if you can test the code on android and let me know if you run into any issues that would be wonderful,

Let me know if you run into any issues
