### ISSUE TITLE
Disconnect message sending triggers exception if server is dead

### ISSUE THREAD

**Issue by tonymrakovcic** [ziicreater/socketcluster-client-ue4#6]
Is this behavior by design or just a weird circumstance?

The flow is:
I start a node server
I start an UE client
I manually kill the server with something like ctrl +c (but I could imagine this happening in real life with an error or something)

If i end the client session, while it is destroying it sends a #disconnect send signal over the socket which in turn tries to free a corrupt address

The flow is this:
https://github.com/ziicreater/socketcluster-client-ue4/blob/2591c31e1c06fdec7e3e216985f7c8dc5e978a5e/SocketCluster/Source/SCClient/Private/SCTransport.cpp#L346

https://github.com/ziicreater/socketcluster-client-ue4/blob/2591c31e1c06fdec7e3e216985f7c8dc5e978a5e/SocketCluster/Source/SCSocket/Private/SCSocket.cpp#L309

https://github.com/ziicreater/socketcluster-client-ue4/blob/2591c31e1c06fdec7e3e216985f7c8dc5e978a5e/SocketCluster/Source/SCSocket/Private/SCSocket.cpp#L179

Is there any way around this? can I do a destroy without a disconnect message?

I don't really want my UE exploding if the server explodes :)

**Comment by SloppyShovel** [comment]
I'm looking into this, I did find an error trying to reproduce this.

https://github.com/ziicreater/socketcluster-client-ue4/blob/2591c31e1c06fdec7e3e216985f7c8dc5e978a5e/SocketCluster/Source/SCClient/Private/SCTransport.cpp#L324

Needs to be :
`_pingTimeoutTicker.BindLambda([&]() {`

**Comment by SloppyShovel** [comment]
Thanks for pointing this issue out @tonymrakovcic 

This issue was related to the client thinking the connection was still open so instead, it was sending a disconnect message to the server when the server already disconnect the connection, the bug has been fixed with this change

https://github.com/ziicreater/socketcluster-client-ue4/blob/master/SocketCluster/Source/SCSocket/Private/SCSocket.cpp#L125

The client will now disconnect with the correct error when it losing connection to the server.
